FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

COPY ["PolyglotAPI.csproj", "."]
RUN dotnet restore "./PolyglotAPI.csproj"
COPY . .

RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Install the VS debugger
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT ["dotnet", "watch", "run", "--non-interactive", "--project", "PolyglotAPI.csproj",  "--launch-profile", "Container (Dockerfile)", "--urls", "http://0.0.0.0:8080"]